version: 2.1

anchor_1: &defaults
  working_directory: ~/ng-in-viewport
  docker:
    - image: circleci/node:11-browsers

anchor_2: &restore_cache_defaults
  keys:
    - ng-in-viewport-{{ .Branch }}-{{ checksum "package.json" }}
    - ng-in-viewport-

general:
  branches:
    only:
      - develop

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - run: xvfb-run -a node --version
      - run: xvfb-run -a yarn --version
      - run: yarn install
      - run: xvfb-run -a yarn run build:lib
      - run: xvfb-run -a yarn run build --progress=false
      - save_cache:
          key: ng-in-viewport-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - run: xvfb-run -a yarn run lint:lib
      - run: xvfb-run -a yarn run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - run: xvfb-run -a yarn run test:lib --watch=false --progress=false --source-map --code-coverage=true --browsers=ChromeHeadlessNoSandbox
      - run: xvfb-run -a yarn run codecov --file=coverage/coverage-summary.json
      # There are no tests yet for example app
      # - run: xvfb-run -a yarn run test --watch=false --progress=false --browsers=ChromeHeadlessNoSandbox

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
