version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:11-browsers
    working_directory: ~/ng-in-viewport

anchor_1: &defaults
  executor: node

anchor_2: &restore_cache_defaults
  keys:
    - ng-in-viewport-{{ .Branch }}-{{ checksum "package.json" }}
    - ng-in-viewport-

general:
  branches:
    only:
      - develop

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - run: xvfb-run -a node --version
      - run: xvfb-run -a yarn --version
      - run: yarn install
      - run: xvfb-run -a yarn run build:lib
      - run: xvfb-run -a yarn run build --progress=false
      - save_cache:
          key: ng-in-viewport-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - run: xvfb-run -a yarn run lint:lib
      - run: xvfb-run -a yarn run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - run: xvfb-run -a yarn run test:lib --watch=false --progress=false --source-map --code-coverage=true --browsers=ChromeHeadlessNoSandbox
      - run: xvfb-run -a mkdir ./tmp
      - run: xvfb-run -a cp ./coverage/lcov.info ./tmp/lib-lcov.info
      # There are no tests yet for example app
      # - run: xvfb-run -a yarn run test --watch=false --progress=false --browsers=ChromeHeadlessNoSandbox
      - persist_to_workspace:
          root: tmp
          paths:
            - lib-lcov.info

  upload_coverage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - run:
          name:  Download cc-test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - run: xvfb-run -a yarn run codecov --file ./tmp/lib-lcov.info
      - run: xvfb-run -a ./tmp/cc-test-reporter format-coverage -t lcov -o ./tmp/codeclimate.lib.json ./tmp/lib-lcov.info
      - run: xvfb-run -a ./tmp/cc-test-reporter upload-coverage -i ./tmp/codeclimate.lib.json

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - upload_coverage
        requires:
          - build
          - test
